### ISSUE TITLE
module 'cv2.dnn' has no attribute 'DictValue'

### ISSUE THREAD

**Issue by SailingB0aty** [Tps-F/sd-webui-blip2#24]
**Describe the bug**
After downloading the repository through the extensions tab in AUTOMATIC1111, when I try to restart the Webui, i get this:

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "S:\New_AUTOMATIC1111\webui\launch.py", line 48, in <module>
    main()
  File "S:\New_AUTOMATIC1111\webui\launch.py", line 44, in main
    start()
  File "S:\New_AUTOMATIC1111\webui\modules\launch_utils.py", line 432, in start
    import webui
  File "S:\New_AUTOMATIC1111\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "S:\New_AUTOMATIC1111\webui\modules\initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "S:\New_AUTOMATIC1111\webui\modules\processing.py", line 14, in <module>
    import cv2
  File "S:\New_AUTOMATIC1111\system\python\lib\site-packages\cv2\__init__.py", line 190, in <module>
    bootstrap()
  File "S:\New_AUTOMATIC1111\system\python\lib\site-packages\cv2\__init__.py", line 184, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "S:\New_AUTOMATIC1111\system\python\lib\site-packages\cv2\__init__.py", line 37, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "importlib\__init__.py", line 126, in import_module
  File "S:\New_AUTOMATIC1111\system\python\lib\site-packages\cv2\typing\__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
Press any key to continue . . .

I am using Windows 10, does anyone have any idea?

**Comment by oaefou** [comment]
sd\venv\Lib\site-packages\cv2\typing\
__init__.py save this file and delete. Reload SD !

**Comment by SailingB0aty** [comment]
> sd\venv\Lib\site-packages\cv2\typing **init**.py save this file and delete. Reload SD !

I love you <3

**Comment by mrmeseeks23** [comment]
Could you clarify what you mean by save AND delete?  I am not 100% certain I understand what you are saying:
1) save init.py and delete the cv2 directory, but place init.py where?  (if location matters)
2) Save init.py and then del init.py (this one didn't make as much sense but I wasn't sure if I was missing something).  I am running linux and I found the cv2 directory.
