### ISSUE TITLE
crashing SD when trying to load

### ISSUE THREAD

**Issue by captainzero93** [Tps-F/sd-webui-blip2#25]
**Describe the bug**
venv "B:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --medvram --opt-split-attention --xformers
Traceback (most recent call last):
  File "B:\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "B:\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "B:\stable-diffusion-webui\modules\launch_utils.py", line 432, in start
    import webui
  File "B:\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "B:\stable-diffusion-webui\modules\initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "B:\stable-diffusion-webui\modules\processing.py", line 14, in <module>
    import cv2
  File "B:\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 190, in <module>
    bootstrap()
  File "B:\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 184, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "B:\stable-diffusion-webui\venv\lib\site-packages\cv2\__init__.py", line 37, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "B:\stable-diffusion-webui\venv\lib\site-packages\cv2\typing\__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'

**To Reproduce**

Latest windows 11, followed all the instructions

**Comment by oaefou** [comment]
https://github.com/Tps-F/sd-webui-blip2/issues/24
