### ISSUE TITLE
How to fix this errors ? sd-webui-blip2

### ISSUE THREAD

**Issue by oaefou** [Tps-F/sd-webui-blip2#4]
Traceback (most recent call last):
File "C:\SD\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
output = await app.get_blocks().process_api(
File "C:\SD\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
result = await self.call_function(
File "C:\SD\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
prediction = await anyio.to_thread.run_sync(
File "C:\SD\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "C:\SD\venv\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "C:\SD\venv\lib\site-packages\anyio_backends_asyncio.py", line 867, in run
result = context.run(func, *args)
File "C:\SD\extensions\sd-webui-blip2\scripts\main.py", line 71, in gen_caption
image = vis_processors["eval"](https://github.com/salesforce/LAVIS/issues/image).unsqueeze(0).to(device)
KeyError: 'eval'

**Comment by Tps-F** [comment]
I think you have not chosen the model
Please select model from model list

**Comment by goblin776655** [comment]
> I think you have not chosen the model Please select model from model list

Same here :(
Model was selected...
Have you test your plugin on windows 10?

**Comment by Tps-F** [comment]
Can you put up all the logs?
I din't verify this with windows 10. I will try it now.

**Comment by goblin776655** [comment]
> Can you put up all the logs? I din't verify this with windows 10. I will try it now.

To create a public link, set `share=True` in `launch()`.
Loading data...
loading model pretrain_opt6.7b...It takes time.
generating...
Traceback (most recent call last):
  File "G:\stable-diffusion\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\stable-diffusion\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable-diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\stable-diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\stable-diffusion\extensions\sd-webui-blip2\scripts\main.py", line 71, in gen_caption
    image = vis_processors["eval"](image).unsqueeze(0).to(device)
KeyError: 'eval'

**Comment by Tps-F** [comment]
It looks like the model is still in the process of being loaded.
When the model has finished loading, `Finish loading model {modeltype}!` is displayed

**Comment by goblin776655** [comment]
> It looks like the model is still in the process of being loaded. When the model has finished loading, `Finish loading model {modeltype}!` is displayed

I've waiting for 10 minutes did not get Finish loading model {modeltype}! :(

**Comment by goblin776655** [comment]
> It looks like the model is still in the process of being loaded. When the model has finished loading, `Finish loading model {modeltype}!` is displayed
I'd find that blip2_pretrained_opt2.7b.pth is on 
G:\stable-diffusion\tmp\.cache\torch\hub\checkpoints\blip2_pretrained_opt2.7b.pth but there is no blip2_pretrained_opt6.7b.pth
looks like pretrain_opt6.7b did not loaded full :( could you plz give me direct link for it to redownload it
Thanks.

**Comment by goblin776655** [comment]
Afer restart 1111 - opt2.7b stoped working too :(

**Comment by oaefou** [comment]
Problem solved. Should have waited for the model to load.

**Comment by Tps-F** [comment]
> > It looks like the model is still in the process of being loaded. When the model has finished loading, `Finish loading model {modeltype}!` is displayed
> 
> I've waiting for 10 minutes did not get Finish loading model {modeltype}! :(

It is extremely long and I'm currently thinking about speeding it up.
